---
- include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution }}.yml'
  - '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_os_family }}.yml'
  tags:
  - ipa_client_install
  - ipa_client_config
  - ipa_client_service

- include: install.yml
  tags: ipa_client_install

- include: config.yml
  tags: ipa_client_config

- include: service.yml
  tags: ipa_client_service
